<Project Sdk="MSTest.Sdk/4.4.1">

  <PropertyGroup>
    <AssemblyName>OsmoOverlay.Tests</AssemblyName>
    <RootNamespace>OsmoOverlay.Tests</RootNamespace>

    <Title>OsmoOverlay Tests</Title>
    <FileDescription>Unit tests for OsmoOverlay.Core.</FileDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OsmoOverlay.Core\OsmoOverlay.Core.csproj" />
  </ItemGroup>

</Project>
